
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: usdf-panda-idds
spec:
  backup:
    retentionPolicy: "15d"
    barmanObjectStore:
      destinationPath: s3://rubin-panda-dev
      endpointURL: http://s3dfrgw.slac.stanford.edu:9000
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-creds
          key: ACCESS_SECRET_KEY
  instances: 2
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: idds
      owner: idds
      secret:
        name: usdf-panda-idds-creds
  
  imageName: ghcr.io/cloudnative-pg/postgresql:14.4-7
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true'

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    parameters:
      shared_buffers: 16GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
#      ldap:
#        scheme: ldaps
#        server: 'ldap-unix.slac.stanford.edu'
#        # tls: true
#        port: 636
#        bindAsAuth:
#          prefix: 'uid='
#          suffix: ',ou=Accounts,dc=slac,dc=stanford,dc=edu'


  resources:
    requests:
      memory: 64Gi
      cpu: 16
    limits:
      memory: 128Gi
      cpu: 32

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 1000Gi


